FROM python:3.11-slim-bullseye as builder

WORKDIR /app

ENV PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_VERSION=1.2.2 \
    POETRY_HOME="/opt/poetry" \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    VIRTUAL_ENVIRONMENT_PATH="/app/.venv"

ENV PATH="$POETRY_HOME/bin:$VIRTUAL_ENVIRONMENT_PATH/bin:$PATH"

RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    curl \
    && curl -sSL https://install.python-poetry.org | python - \
    && apt-get purge --auto-remove -y \
    build-essential \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ./poetry.lock ./pyproject.toml ./README.rst ./
RUN poetry install --no-interaction --no-root --without dev -vvv

COPY protohackers ./protohackers
RUN poetry build --no-interaction -f wheel

FROM python:3.11-alpine as runtime

WORKDIR /app

ENV PATH="/app/.venv/bin:/app/.venv/lib/python3.11/site-packages/bin:$PATH"

COPY ./entrypoint.sh ./
COPY --from=builder /app/.venv /app/.venv
COPY --from=builder /app/dist/*.whl ./
RUN pip install *.whl --target=/app/.venv/lib/python3.11/site-packages/ --no-deps

ENTRYPOINT [ "./entrypoint.sh" ]
